### ISSUE TITLE
No module named skip_thoughts

### ISSUE THREAD

**Issue by 271215pa** [xcodebugger/text_to_image_synthesis#1]
I am getting this error after running this ---> python main.py

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from model import DeConvNET
  File "/home/pa/text_to_image_synthesis/model.py", line 20, in <module>
    from coco_manager import COCOManager
  File "/home/pa/text_to_image_synthesis/coco_manager.py", line 5, in <module>
    from skip_thoughts import configuration
ImportError: No module named skip_thoughts

It seems like there was a folder named skip_thoughts.
Help !

**Comment by xcodebugger** [comment]
Hey, download the skip_thoughts folder from https://github.com/tensorflow/models/tree/master/research/skip_thoughts

Then you need to create model directory in the skip_thoughts folder, and download the pretrained model as it is explained in the link that I've attached.

And I don't remember exactly, I believe I had to download and install NLTK(The link is given in the page).

If I get some time, I will add README file.
Thanks.
